### ISSUE TITLE
Support for newest versions

### ISSUE THREAD

**Issue by gugacavalieri** [abnamrocoesd/neo4j-data-migrations#5]
Hey guys, I have just seen that `neo4j-driver` has dropped support for the `v1` namespace.

So this lib is not working anymore for the newer versions of `neo4j-driver`.

Is there any plans to support the newer versions? 

I can help out with that if it is of any interest :)

**Comment by remcohendriks** [comment]
Hi, I've added a major version v2 which supports neo4j-driver v4.
Neo4j-driver v1 can still use the v1 releases.
Let me know if this works for you.
